import SteamUser from '../index';

import EAccountFlags from '../enums/EAccountFlags';
import EAccountType from '../enums/EAccountType';
import EActivationCodeClass from '../enums/EActivationCodeClass';
import EAppInfoSection from '../enums/EAppInfoSection';
import EAppUsageEvent from '../enums/EAppUsageEvent';
import EAudioFormat from '../enums/EAudioFormat';
import EAuthSessionResponse from '../enums/EAuthSessionResponse';
import EBillingType from '../enums/EBillingType';
import EBroadcastWatchLocation from '../enums/EBroadcastWatchLocation';
import EChatAction from '../enums/EChatAction';
import EChatActionResult from '../enums/EChatActionResult';
import EChatEntryType from '../enums/EChatEntryType';
import EChatFlags from '../enums/EChatFlags';
import EChatInfoType from '../enums/EChatInfoType';
import EChatMemberStateChange from '../enums/EChatMemberStateChange';
import EChatPermission from '../enums/EChatPermission';
import EChatRoomEnterResponse from '../enums/EChatRoomEnterResponse';
import EChatRoomGroupRank from '../enums/EChatRoomGroupRank';
import EChatRoomJoinState from '../enums/EChatRoomJoinState';
import EChatRoomMemberStateChange from '../enums/EChatRoomMemberStateChange';
import EChatRoomNotificationLevel from '../enums/EChatRoomNotificationLevel';
import EChatRoomServerMessage from '../enums/EChatRoomServerMessage';
import EChatRoomType from '../enums/EChatRoomType';
import EClanPermission from '../enums/EClanPermission';
import EClanRank from '../enums/EClanRank';
import EClanRelationship from '../enums/EClanRelationship';
import EClientPersonaStateFlag from '../enums/EClientPersonaStateFlag';
import EClientStat from '../enums/EClientStat';
import EClientStatAggregateMethod from '../enums/EClientStatAggregateMethod';
import EContentDownloadSourceType from '../enums/EContentDownloadSourceType';
import EControllerLayoutType from '../enums/EControllerLayoutType';
import ECurrencyCode from '../enums/ECurrencyCode';
import EDenyReason from '../enums/EDenyReason';
import EDepotFileFlag from '../enums/EDepotFileFlag';
import EDRMBlobDownloadErrorDetail from '../enums/EDRMBlobDownloadErrorDetail';
import EDRMBlobDownloadType from '../enums/EDRMBlobDownloadType';
import EEconTradeResponse from '../enums/EEconTradeResponse';
import EFrameAccumulatedStat from '../enums/EFrameAccumulatedStat';
import EFriendFlags from '../enums/EFriendFlags';
import EFriendRelationship from '../enums/EFriendRelationship';
import EGameSearchAction from '../enums/EGameSearchAction';
import EGameSearchResult from '../enums/EGameSearchResult';
import EHIDDeviceDisconnectMethod from '../enums/EHIDDeviceDisconnectMethod';
import EHIDDeviceLocation from '../enums/EHIDDeviceLocation';
import EIntroducerRouting from '../enums/EIntroducerRouting';
import EJSRegisterMethodType from '../enums/EJSRegisterMethodType';
import EKeyEscrowUsage from '../enums/EKeyEscrowUsage';
import ELeaderboardDataRequest from '../enums/ELeaderboardDataRequest';
import ELeaderboardDisplayType from '../enums/ELeaderboardDisplayType';
import ELeaderboardSortMethod from '../enums/ELeaderboardSortMethod';
import ELeaderboardUploadScoreMethod from '../enums/ELeaderboardUploadScoreMethod';
import ELicenseFlags from '../enums/ELicenseFlags';
import ELicenseType from '../enums/ELicenseType';
import ELogFileType from '../enums/ELogFileType';
import EMarketingMessageFlags from '../enums/EMarketingMessageFlags';
import EMsg from '../enums/EMsg';
import ENewsUpdateType from '../enums/ENewsUpdateType';
import ENotificationSetting from '../enums/ENotificationSetting';
import EOSType from '../enums/EOSType';
import EPaymentMethod from '../enums/EPaymentMethod';
import EPersonaState from '../enums/EPersonaState';
import EPersonaStateFlag from '../enums/EPersonaStateFlag';
import EPlatformType from '../enums/EPlatformType';
import EProtoExecutionSite from '../enums/EProtoExecutionSite';
import EPublishedFileForSaleStatus from '../enums/EPublishedFileForSaleStatus';
import EPublishedFileVisibility from '../enums/EPublishedFileVisibility';
import EPurchaseResultDetail from '../enums/EPurchaseResultDetail';
import ERegionCode from '../enums/ERegionCode';
import ERemoteClientBroadcastMsg from '../enums/ERemoteClientBroadcastMsg';
import ERemoteClientService from '../enums/ERemoteClientService';
import ERemoteDeviceAuthorizationResult from '../enums/ERemoteDeviceAuthorizationResult';
import ERemoteDeviceStreamingResult from '../enums/ERemoteDeviceStreamingResult';
import ERemoteStoragePlatform from '../enums/ERemoteStoragePlatform';
import EResult from '../enums/EResult';
import EServerFlags from '../enums/EServerFlags';
import EServerType from '../enums/EServerType';
import EStreamActivity from '../enums/EStreamActivity';
import EStreamAudioCodec from '../enums/EStreamAudioCodec';
import EStreamBitrate from '../enums/EStreamBitrate';
import EStreamChannel from '../enums/EStreamChannel';
import EStreamControlMessage from '../enums/EStreamControlMessage';
import EStreamDataMessage from '../enums/EStreamDataMessage';
import EStreamDiscoveryMessage from '../enums/EStreamDiscoveryMessage';
import EStreamFrameEvent from '../enums/EStreamFrameEvent';
import EStreamFramerateLimiter from '../enums/EStreamFramerateLimiter';
import EStreamFrameResult from '../enums/EStreamFrameResult';
import EStreamGamepadInputType from '../enums/EStreamGamepadInputType';
import EStreamingDataType from '../enums/EStreamingDataType';
import EStreamMouseButton from '../enums/EStreamMouseButton';
import EStreamMouseWheelDirection from '../enums/EStreamMouseWheelDirection';
import EStreamQualityPreference from '../enums/EStreamQualityPreference';
import EStreamStatsMessage from '../enums/EStreamStatsMessage';
import EStreamVersion from '../enums/EStreamVersion';
import EStreamVideoCodec from '../enums/EStreamVideoCodec';
import ESystemIMType from '../enums/ESystemIMType';
import EUCMFilePrivacyState from '../enums/EUCMFilePrivacyState';
import EUdpPacketType from '../enums/EUdpPacketType';
import EUniverse from '../enums/EUniverse';
import EVideoFormat from '../enums/EVideoFormat';
import EWorkshopEnumerationType from '../enums/EWorkshopEnumerationType';
import EWorkshopFileAction from '../enums/EWorkshopFileAction';
import EWorkshopFileType from '../enums/EWorkshopFileType';


SteamUser['EAccountFlags'] = EAccountFlags;
SteamUser['EAccountType'] = EAccountType;
SteamUser['EActivationCodeClass'] = EActivationCodeClass;
SteamUser['EAppInfoSection'] = EAppInfoSection;
SteamUser['EAppUsageEvent'] = EAppUsageEvent;
SteamUser['EAudioFormat'] = EAudioFormat;
SteamUser['EAuthSessionResponse'] = EAuthSessionResponse;
SteamUser['EBillingType'] = EBillingType;
SteamUser['EBroadcastWatchLocation'] = EBroadcastWatchLocation;
SteamUser['EChatAction'] = EChatAction;
SteamUser['EChatActionResult'] = EChatActionResult;
SteamUser['EChatEntryType'] = EChatEntryType;
SteamUser['EChatFlags'] = EChatFlags;
SteamUser['EChatInfoType'] = EChatInfoType;
SteamUser['EChatMemberStateChange'] = EChatMemberStateChange;
SteamUser['EChatPermission'] = EChatPermission;
SteamUser['EChatRoomEnterResponse'] = EChatRoomEnterResponse;
SteamUser['EChatRoomGroupRank'] = EChatRoomGroupRank;
SteamUser['EChatRoomJoinState'] = EChatRoomJoinState;
SteamUser['EChatRoomMemberStateChange'] = EChatRoomMemberStateChange;
SteamUser['EChatRoomNotificationLevel'] = EChatRoomNotificationLevel;
SteamUser['EChatRoomServerMessage'] = EChatRoomServerMessage;
SteamUser['EChatRoomType'] = EChatRoomType;
SteamUser['EClanPermission'] = EClanPermission;
SteamUser['EClanRank'] = EClanRank;
SteamUser['EClanRelationship'] = EClanRelationship;
SteamUser['EClientPersonaStateFlag'] = EClientPersonaStateFlag;
SteamUser['EClientStat'] = EClientStat;
SteamUser['EClientStatAggregateMethod'] = EClientStatAggregateMethod;
SteamUser['EContentDownloadSourceType'] = EContentDownloadSourceType;
SteamUser['EControllerLayoutType'] = EControllerLayoutType;
SteamUser['ECurrencyCode'] = ECurrencyCode;
SteamUser['EDenyReason'] = EDenyReason;
SteamUser['EDepotFileFlag'] = EDepotFileFlag;
SteamUser['EDRMBlobDownloadErrorDetail'] = EDRMBlobDownloadErrorDetail;
SteamUser['EDRMBlobDownloadType'] = EDRMBlobDownloadType;
SteamUser['EEconTradeResponse'] = EEconTradeResponse;
SteamUser['EFrameAccumulatedStat'] = EFrameAccumulatedStat;
SteamUser['EFriendFlags'] = EFriendFlags;
SteamUser['EFriendRelationship'] = EFriendRelationship;
SteamUser['EGameSearchAction'] = EGameSearchAction;
SteamUser['EGameSearchResult'] = EGameSearchResult;
SteamUser['EHIDDeviceDisconnectMethod'] = EHIDDeviceDisconnectMethod;
SteamUser['EHIDDeviceLocation'] = EHIDDeviceLocation;
SteamUser['EIntroducerRouting'] = EIntroducerRouting;
SteamUser['EJSRegisterMethodType'] = EJSRegisterMethodType;
SteamUser['EKeyEscrowUsage'] = EKeyEscrowUsage;
SteamUser['ELeaderboardDataRequest'] = ELeaderboardDataRequest;
SteamUser['ELeaderboardDisplayType'] = ELeaderboardDisplayType;
SteamUser['ELeaderboardSortMethod'] = ELeaderboardSortMethod;
SteamUser['ELeaderboardUploadScoreMethod'] = ELeaderboardUploadScoreMethod;
SteamUser['ELicenseFlags'] = ELicenseFlags;
SteamUser['ELicenseType'] = ELicenseType;
SteamUser['ELogFileType'] = ELogFileType;
SteamUser['EMarketingMessageFlags'] = EMarketingMessageFlags;
SteamUser['EMsg'] = EMsg;
SteamUser['ENewsUpdateType'] = ENewsUpdateType;
SteamUser['ENotificationSetting'] = ENotificationSetting;
SteamUser['EOSType'] = EOSType;
SteamUser['EPaymentMethod'] = EPaymentMethod;
SteamUser['EPersonaState'] = EPersonaState;
SteamUser['EPersonaStateFlag'] = EPersonaStateFlag;
SteamUser['EPlatformType'] = EPlatformType;
SteamUser['EProtoExecutionSite'] = EProtoExecutionSite;
SteamUser['EPublishedFileForSaleStatus'] = EPublishedFileForSaleStatus;
SteamUser['EPublishedFileVisibility'] = EPublishedFileVisibility;
SteamUser['EPurchaseResultDetail'] = EPurchaseResultDetail;
SteamUser['ERegionCode'] = ERegionCode;
SteamUser['ERemoteClientBroadcastMsg'] = ERemoteClientBroadcastMsg;
SteamUser['ERemoteClientService'] = ERemoteClientService;
SteamUser['ERemoteDeviceAuthorizationResult'] = ERemoteDeviceAuthorizationResult;
SteamUser['ERemoteDeviceStreamingResult'] = ERemoteDeviceStreamingResult;
SteamUser['ERemoteStoragePlatform'] = ERemoteStoragePlatform;
SteamUser['EResult'] = EResult;
SteamUser['EServerFlags'] = EServerFlags;
SteamUser['EServerType'] = EServerType;
SteamUser['EStreamActivity'] = EStreamActivity;
SteamUser['EStreamAudioCodec'] = EStreamAudioCodec;
SteamUser['EStreamBitrate'] = EStreamBitrate;
SteamUser['EStreamChannel'] = EStreamChannel;
SteamUser['EStreamControlMessage'] = EStreamControlMessage;
SteamUser['EStreamDataMessage'] = EStreamDataMessage;
SteamUser['EStreamDiscoveryMessage'] = EStreamDiscoveryMessage;
SteamUser['EStreamFrameEvent'] = EStreamFrameEvent;
SteamUser['EStreamFramerateLimiter'] = EStreamFramerateLimiter;
SteamUser['EStreamFrameResult'] = EStreamFrameResult;
SteamUser['EStreamGamepadInputType'] = EStreamGamepadInputType;
SteamUser['EStreamingDataType'] = EStreamingDataType;
SteamUser['EStreamMouseButton'] = EStreamMouseButton;
SteamUser['EStreamMouseWheelDirection'] = EStreamMouseWheelDirection;
SteamUser['EStreamQualityPreference'] = EStreamQualityPreference;
SteamUser['EStreamStatsMessage'] = EStreamStatsMessage;
SteamUser['EStreamVersion'] = EStreamVersion;
SteamUser['EStreamVideoCodec'] = EStreamVideoCodec;
SteamUser['ESystemIMType'] = ESystemIMType;
SteamUser['EUCMFilePrivacyState'] = EUCMFilePrivacyState;
SteamUser['EUdpPacketType'] = EUdpPacketType;
SteamUser['EUniverse'] = EUniverse;
SteamUser['EVideoFormat'] = EVideoFormat;
SteamUser['EWorkshopEnumerationType'] = EWorkshopEnumerationType;
SteamUser['EWorkshopFileAction'] = EWorkshopFileAction;
SteamUser['EWorkshopFileType'] = EWorkshopFileType;
